### ISSUE TITLE
Share code with https://github.com/os-autoinst/os-autoinst/blob/master/crop.py ?

### ISSUE THREAD

**Issue by okurz** [alapha23/needle_puncher#1]
Hi, Yifan made me aware of this repo. It is a pretty cool idea. For further steps you might be interested to look into https://github.com/os-autoinst/os-autoinst/blob/master/crop.py which is already an "offline needle editor" so missing the connection to the VNC server as you have accomplished but it offers some other ideas as well.

**Comment by alapha23** [comment]
Thank you for suggesting that! 
I was using that script before and thinking that it could be better if we have a few buttons and it captures running qemu instances. So I made this repo. 

I actually borrowed some ideas and a python class from that script. We use tkinter and we use arrow keys to adjust areas. 
So I updated the readme to indicate that I was inspired by that script. I forgot to do that before, sorry for the delay!

**Comment by okurz** [comment]
Well, I guess that solves this issue :) Thanks!
